-- create database,
CREATE DATABASE final_ecommerce_db;

-- run this query after running the application, tables are autogenerated
INSERT INTO roles (id, name) VALUES (1, 'ROLE_ADMIN'), (2, 'ROLE_USER');